# This workflow runs the Smartsheet job number generation script

name: Generate Smartsheet Job Numbers

on:
  # 1. Schedule: Runs automatically. This example runs at 8 AM UTC every weekday.
  #    Use https://crontab.guru to customize your schedule.
  schedule:
    - cron: '0 8 * * 1-5'

  # 2. Manual Trigger: Allows you to run the workflow manually from the GitHub Actions tab.
  workflow_dispatch:

jobs:
  run-smartsheet-script:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository's code so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installs the necessary Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartsheet-python-sdk

      # Runs your Python script
      - name: Execute Job Number Script
        env:
          # This pulls the API token from your repository's secrets
          SMARTSHEET_API_TOKEN: ${{ secrets.SMARTSHEET_API_TOKEN }}
        run: python generate_job_numbers.py
